# Generated by Django 5.2 on 2025-05-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-code', help_text="Font Awesome class name (e.g. 'fa-python')", max_length=50),
        ),
    ]
