# Generated by Django 5.2 on 2025-05-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_privacy_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_nickname',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
