# Generated by Django 5.2 on 2025-05-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_dead_line'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['dead_line'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
