# Generated by Django 5.2 on 2025-05-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=8, unique=True),
        ),
    ]
